- .gitlab-ci.yml
- README.md
- plex/Dockerfile
- plex/config.json
Adds support for ARM-based devices
> Arm support

- README.md
Fixed the domain in the Readme file for the claim link from .com to .tv
> Fixed domain

- plex/Dockerfile
As the titles says, the Plex Media Server notified me with that annoying banner.
> ⬆️ Upgrades Plex Media Server to 1.16.5.1554

- plex/Dockerfile
> Updated the Media Server to the newest version
> ⬆️ Upgrades Plex Media Server to 1.18.5.2309

- plex/Dockerfile
Update Plex Media Server to 1.20.1.3252
> ⬆️ Upgrades Plex Media Server to 1.20.1.3252

- LICENSE.md
- README.md
- plex/.README.j2
- plex/DOCS.md
> Happy New Year

- plex/Dockerfile
Update Plex Media Server to 1.21.1.3830
> ⬆️ Upgrades Plex Media Server to 1.21.1.3876

- plex/Dockerfile
- plex/build.json
Upgrades the add-on base image to the latest and greatest version
> Upgrade add-on base image to 6.1.0

- plex/Dockerfile
- plex/build.json
Upgrades add-on base image to 6.1.1
> Upgrade add-on base image to 6.1.1

- plex/Dockerfile
Upgrades Plex Media Server to the latest version.
> :arrow_up: Upgrades Plex Media Server to 1.21.2.3939

- plex/Dockerfile
- plex/build.json
Upgrade add-on base image to 6.1.3
fixes #62
> Upgrade add-on base image to 6.1.3

- plex/Dockerfile
Upgrades Plex Media Server to 1.21.3.4046
> :arrow_up: Upgrades Plex Media Server to 1.21.3.4046

- plex/Dockerfile
- plex/build.json
Upgrades add-on base image to v6.1.4
> ⬆️ Upgrades add-on base image to v6.1.4

- plex/Dockerfile
Upgrades Plex Media Server to 1.22.2.4282/
> ⬆️ Upgrades Plex Media Server to 1.22.2.4282

- plex/Dockerfile
- plex/build.json
Upgrades add-on base image to v6.2.0
> Upgrades add-on base image to v6.2.0

- plex/translations/en.yaml
Adds translations for the English language.
> Add translation support

- plex/Dockerfile
Upgrades Plex Media Server to 1.22.3.4392
> ⬆️ Upgrades Plex Media Server to 1.22.3.4392

- README.md
Updating the readme contributing link to point to the correct file.
#89
> Correct the link to CONTRIBUTING.md

- plex/Dockerfile
Upgrades Plex Media Server to 1.23.2.4656
> ⬆️ Upgrades Plex Media Server to 1.23.2.4656

- plex/Dockerfile
- plex/build.json
Upgrades add-on base image to v6.2.1
> ⬆️ Upgrades add-on base image to v6.2.1

- plex/Dockerfile
Upgrades Plex Media Server to 1.23.4.4805
> ⬆️ Upgrades Plex Media Server to 1.23.4.4805

- plex/Dockerfile
Upgrades Plex Media Server to 1.24.0.4930
> ⬆️ Upgrades Plex Media Server to 1.24.0.4930

- plex/Dockerfile
Upgrades Plex Media Server to 1.25.2.5319
> :arrow_up: Upgrades Plex Media Server to 1.25.2.5319

- plex/Dockerfile
> Update plex to 1.25.3.5385 (Newest version)
> ⬆️ Update plex to 1.25.3.5385

- LICENSE.md
- README.md
- plex/.README.j2
- plex/DOCS.md
> :fireworks: Updates maintenance/license year to 2022

- plex/Dockerfile
Upgrades Plex Media Server to 1.25.3.5409
> Upgrades Plex Media Server to 1.25.3.5409
> ⬆️ Upgrades Plex Media Server to 1.25.3.5409

- plex/Dockerfile
> Upgrades Plex Media Server to 1.25.3.5409
> ⬆️ Upgrades Plex Media Server to 1.25.5.5492

- plex/Dockerfile
>Upgrades Plex Media Server to 1.25.6.5577
> ⬆️ Upgrades Plex Media Server to 1.25.6.5577

- plex/Dockerfile
Upgrades Plex Media Server to 1.25.7.5604
> :arrow_up: Upgrades Plex Media Server to 1.25.7.5604

- plex/DOCS.md
Making it easier to find the add-on
> :books: Add My buttons to documentation

- plex/Dockerfile
Upgrades Plex Media Server to 1.26.0.5715
> :arrow_up: Upgrades Plex Media Server to 1.26.0.5715

- README.md
- plex/Dockerfile
- plex/build.yaml
- plex/config.yaml
- plex/rootfs/etc/cont-init.d/plex.sh
- plex/rootfs/etc/cont-init.d/webtools.sh
- plex/rootfs/etc/services.d/plex/finish
- plex/rootfs/etc/services.d/plex/run
Upgrades add-on base image to 8.0.0
Drops i386 support. Ubuntu doesn't support that anymore.
> ⬆️ Upgrades add-on base image to 8.0.0

- plex/DOCS.md
Making things just a tiny bit easier
> :books: Use new My Home Assistant link format

- plex/Dockerfile
Upgrades Plex Media Server to 1.26.2.5797
closes #152
> ⬆️ Upgrades Plex Media Server to 1.26.2.5797

- plex/Dockerfile
- plex/build.yaml
Upgrades add-on base image to 8.1.0
> ⬆️ Upgrades add-on base image to 8.1.0

- plex/Dockerfile
Upgrades Plex Media Server to 1.28.1.6104
> ⬆️ Upgrades Plex Media Server to 1.28.1.6104

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 8.1.1

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.28.2.6151

- plex/rootfs/etc/cont-init.d/plex.sh
Allow setting a new claim code to re-auth the server.
fixes #165
> Allow re-auth by setting new claim code

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 8.1.2

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.29.1.6260

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 8.2.0

- LICENSE.md
- README.md
- plex/.README.j2
- plex/DOCS.md
> :fireworks: Updates maintenance/license year to 2023

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 8.2.1

- plex/Dockerfile
Upgrade Plex Media Server to 1.30.1.6562
None
> ⬆️ Upgrades Plex Media Server to 1.30.1.6562

- plex/Dockerfile
> upgrading to 1.31.0.6654
> It seemed at first I could not add libraries, but after a while I could.
> ⬆️ Update Plex Media Server to 1.31.0.6654

- plex/Dockerfile
Upgrade Plex Version to current latest - 1.31.2.6810
> chore: update Plex Media Server to 1.31.2.6810

- plex/DOCS.md
> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
> Fix broken URL

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.31.3.6868

- plex/Dockerfile
Upgrade Plex to latest public release
None
> ⬆️ Upgrades Plex Media Server to 1.32.4.7195

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 9.0.0

- plex/Dockerfile
> Install Plex Media Server from Debian package

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.32.5.7349

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.32.6.7557

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades add-on base image to 9.0.1

- plex/Dockerfile
https://forums.plex.tv/t/plex-media-server/30447/605
> ⬆️ Upgrades Plex Media Server to 1.32.7.7621

- plex/Dockerfile
- plex/build.yaml
SSIA, seen some segfaults on Ubuntu, avoiding and using the more stable Debian.
> Migrate from Ubuntu to Debian

- LICENSE.md
- README.md
- plex/.README.j2
- plex/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- plex/Dockerfile
new version of the underlying Plux server (1.32.8.7639)
> Install version 1.32.8.7639 of Plex Media Server

- plex/Dockerfile
- plex/build.yaml
> ⬆️ Upgrades base image to 7.3.3

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.40.0.7998

- plex/Dockerfile
> ⬆️ Upgrades Plex Media Server to 1.40.2.8395

- LICENSE.md
- README.md
- plex/.README.j2
- plex/DOCS.md
> :fireworks: Updates maintenance/license year to 2025
